apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["llama/userdb"]'
    management.cattle.io/ui-managed: 'true'
  creationTimestamp: '2024-03-07T05:08:41Z'
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/targetWorkloadIds: {}
            f:management.cattle.io/ui-managed: {}
          f:ownerReferences:
            .: {}
            k:{"uid":"e45cf4a1-1786-4557-9db3-d089313d0724"}: {}
        f:spec:
          f:internalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":6379,"protocol":"TCP"}:
              .: {}
              f:name: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: agent
      operation: Update
      time: '2024-03-07T05:08:41Z'
  name: userdb
  namespace: llama
  ownerReferences:
    - apiVersion: apps/v1
      controller: true
      kind: Deployment
      name: userdb
      uid: e45cf4a1-1786-4557-9db3-d089313d0724
  resourceVersion: '291655486'
  uid: b521fe1c-57e6-4000-b496-87801632138b
spec:
  clusterIP: 10.43.247.84
  clusterIPs:
    - 10.43.247.84
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: db
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-llama-userdb
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
